#+ summary: Count genomic features in a genome graph.
#+ tags:
#+  - Count genomic features
#+ enumerate:
#+  - graph:
#+    - http://solgenomics.net/genome/Solanum_lycopersicum
#+    - http://solgenomics.net/genome/Solanum_pennellii
#+    - http://solgenomics.net/genome/Solanum_tuberosum
#+    - http://plants.ensembl.org/Solanum_lycopersicum
#+    - http://plants.ensembl.org/Solanum_tuberosum

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT
  ?feature_id
  ?feature_uri
  ?feature
  COUNT(*) AS ?n
FROM ?_graph_iri
FROM <http://purl.obolibrary.org/obo/so.owl>
WHERE {
  ?f a ?feature_uri .
  ?feature_uri rdfs:label ?feature .
  FILTER regex(?feature_uri, obo:SO_) .
  BIND(replace(replace(str(?feature_uri), '.+\\/', ''), '_', ':') AS ?feature_id)
}
GROUP BY ?feature_id ?feature_uri ?feature
ORDER BY DESC(?n)
