#+ summary: Get genomic features given an interval.
#+ tags:
#+  - Get genomic features given an interval
#+ enumerate:
#+  - graph:
#+    - http://solgenomics.net/genome/Solanum_lycopersicum
#+    - http://solgenomics.net/genome/Solanum_pennellii
#+    - http://solgenomics.net/genome/Solanum_tuberosum
#+ defaults:
#   - chromosome: 10
#+  - start: 58895882
#+  - end: 59082990

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>

SELECT
   ?feature_id
   ?begin_ref AS ?chr
   ?begin_pos
   ?end_pos
WHERE {
   GRAPH ?_graph_iri { 
      ?feature a ?feature_type ;
         dcterms:identifier ?feature_id ;
         faldo:location ?loc .
      ?loc faldo:begin ?begin ;
         faldo:end ?end .
      ?begin faldo:position ?begin_pos ;
         faldo:reference/rdfs:label ?begin_ref . 
      ?end faldo:position ?end_pos ; 
         faldo:reference/rdfs:label ?end_ref .
      FILTER(?begin_pos >= ?_start &&
             ?end_pos <= ?_end &&
             ?begin_ref = ?end_ref &&
             ?begin_ref = ?_chromosome)
   }
}
