#+ summary: Get genes contained in a QTL.
#+ tags:
#+  - Get genes contained in a QTL
#+ defaults:
#+  - qtlid: QTL:3859326_3_2

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>
SELECT
  ?gene_id
  ?gene_uri
FROM <http://solgenomics.net/genome/Solanum_lycopersicum>
FROM <http://solgenomics.net/genome/Solanum_tuberosum>
FROM <http://europepmc.org/articles>
WHERE {
  ?gene_uri a obo:SO_0001217 ;
    dcterms:identifier ?gene_id .
  ?qtl_uri a obo:SO_0000771 ;
    dcterms:identifier ?_qtlid ;
    so:overlaps ?gene_uri .
}
