#+ summary:  Get annotations from SGN given a gene ID.
#+ tags:
#+  - Get annotations from SGN given a gene ID
#+ defaults:
#+  - geneid: Solyc01g005000.2

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>
PREFIX bif: <bif:>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT
   ?gene_uri
   ?gene_annotations
FROM <http://solgenomics.net/genome/Solanum_lycopersicum>
FROM <http://solgenomics.net/genome/Solanum_pennellii>
FROM <http://solgenomics.net/genome/Solanum_tuberosum>
WHERE {
   ?gene_uri a obo:SO_0001217 ;
      dcterms:identifier ?_geneid_xsd_string ;
      so:transcribed_to ?transcript .                
   ?transcript rdfs:comment ?gene_annotations
}
