#+ summary: Get orthologous genes.
#+ tags:
#+  - Get orthologous genes
#+ defaults:
#+  - geneid: Solyc01g005000.2

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX is_orthologous_to: <http://semanticscience.org/resource/SIO_000558>
PREFIX Gene: <http://purl.obolibrary.org/obo/SO_0001217>

SELECT
   ?gene_id
   ?gene_uri
   ?ortholog_id
   ?ortholog_uri
FROM <http://plants.ensembl.org/Solanum_lycopersicum>
FROM <http://plants.ensembl.org/Solanum_tuberosum>
FROM <http://www.uniprot.org/proteomes/Solanum_lycopersicum>
FROM <http://www.uniprot.org/proteomes/Solanum_tuberosum>
WHERE {
   ?gene_uri a Gene: ;
      dc:identifier ?gene_id ;
      is_orthologous_to: ?ortholog_uri .
   ?ortholog_uri a Gene: ;
      dc:identifier ?ortholog_id
   FILTER(?gene_id = ?_geneid)
}
