#+ summary: Get QTLs associated with a trait identified by ID.
#+ tags:
#+  - Get QTLs associated with a trait
#+ defaults:
#+  - traitid: SP:0000201

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT
   ?qtl_id
FROM <http://europepmc.org>
WHERE {
   ?qtl a obo:SO_0000771 ;
      dcterms:identifier ?qtl_id ;
      obo:RO_0003308 ?trait_id .
   BIND(URI(CONCAT(obo:, REPLACE(?_traitid, ':', '_'))) AS ?trait_id)
}
