#+ summary: List traits (i.e. terms from PO, TO and SPTO ontologies) and associated QTLs.
#+ tags:
#+      - CandyGene (Example 6) - Doesn't work...
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT
   DISTINCT concat('[', ?trait_id, '](', ?trait, ')') AS ?trait_id
   str(?trait_name) AS ?trait_name
   COUNT(?qtl) AS ?n_qtls
FROM <http://europepmc.org/articles>
WHERE {
   ?qtl a obo:SO_0000771 ;
      obo:RO_0003308 ?trait .
   {
      SELECT
         ?trait
         ?trait_name
         ?trait_id
      FROM <http://purl.obolibrary.org/obo/po.owl>
      FROM <http://purl.obolibrary.org/obo/to.owl>
      FROM <http://purl.bioontology.org/ontology/SPTO> {
         ?trait rdfs:label ?trait_name ;
            <http://www.geneontology.org/formats/oboInOwl#id> ?trait_id .
      }
   }
}
ORDER BY ?trait_name
