#+ summary:  List all QTLs in an article
#+ tags:
#+  - List all QTLs all QTLs in an article with PMC_id

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>
PREFIX bif: <bif:> 

SELECT
   ?qtl_uri
   ?qtl_id
   ?pmc_id 
WHERE {
   GRAPH <http://europepmc.org/articles> {
      ?qtl_uri a obo:SO_0000771 ;
          dcterms:identifier ?qtl_id;
          dcterms:isReferencedBy ?pmc_id.          
      
      BIND(uri(concat("http://identifiers.org/pmc/", ?_pmc_id )) AS ?user_pmc_id)      


      BIND(bif:strcontains(?pmc_id,?user_pmc_id ) AS ?match)
      FILTER(?match = 1)
   }
}

# EXAMPLE: ?pmc_id = PMC4266912
