#+ summary:  List Traitid for given trait_name
#+ tags:
#+  - List all genes associated with a QTL(s) given a trait ID

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>

SELECT
   ?qtl_id
   ?gene_id
   ?gene_name
WHERE {
   GRAPH <http://europepmc.org/articles> {
      ?qtl_uri a obo:SO_0000771 ;
               dcterms:identifier ?qtl_id;         
               so:overlaps ?gene_uri ;
               obo:RO_0003308 ?trait_id .
      BIND(uri(concat(obo:, replace(?_trait_id, ':', '_'))) AS ?trait_id)
   }
   GRAPH <http://solgenomics.net/genome/Solanum_lycopersicum> {
      ?gene_uri rdfs:label ?gene_name ;
                dcterms:identifier ?gene_id; 
                rdf:type obo:SO_0001217.
   }
}


# EXAMPLE: ?trait_id SP:0000012

