#+ summary:  List all articles containing a trait term
#+ tags:
#+  - List all articles containing a trait term

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bif: <bif:>
SELECT
   ?pmc_id
   ?trait_id
   str(?trait_term) AS ?trait_term
   
FROM <http://europepmc.org/articles>
WHERE {
   ?qtl a obo:SO_0000771 ;
      dcterms:isReferencedBy ?pmc_id;   
      obo:RO_0003308 ?trait .
   {
      SELECT
         ?trait
         ?trait_term
         ?trait_id
      FROM <http://purl.obolibrary.org/obo/po.owl>
      FROM <http://purl.obolibrary.org/obo/to.owl>
      FROM <http://purl.bioontology.org/ontology/SPTO> {
         ?trait rdfs:label ?trait_term ;
            <http://www.geneontology.org/formats/oboInOwl#id> ?trait_id .
         ?trait_name bif:contains ?_trait_term.
      }
   }
}
ORDER BY ?trait_name

# EXAMPLE: trait_term: yield
