#+ summary:  List Traitid for given trait_name
#+ tags:
#+  - List all QTLs related given trait_id

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>

SELECT
   ?qtl_uri
   ?qtl_id 
WHERE {
   GRAPH <http://europepmc.org/articles> {
      ?qtl_url a obo:SO_0000771 ;
          dcterms:identifier ?qtl_id;          
             obo:RO_0003308 ?trait_id .
      BIND(uri(concat(obo:, replace(?_trait_id, ':', '_'))) AS ?trait_id)
   }
}

# EXAMPLE: SP:0000012
