#+ summary:  Get potato_gene orthologs for tomato gene_ids.
#+ tags:
#+  - Get ortholgos

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>
PREFIX bif: <bif:> 
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT
   DISTINCT
   ?potato_gene_id  
   ?tomato_gene_id
WHERE{
    GRAPH <http://plants.ensembl.org/Solanum_tuberosum> {
        ?potato_gene sio:SIO_000558 ?ensemble_gene_id;
                     dc:identifier ?potato_gene_id. 

    }
    GRAPH<http://solgenomics.net/genome/Solanum_lycopersicum>{
        ?tomato_gene a obo:SO_0001217;
                     dcterms:identifier ?tomato_gene_id; 
                     owl:sameAs ?ensemble_gene_id.
    
    
    } 
    BIND(bif:strcontains(?potato_gene_id,?_potatogene_id ) AS ?match)
      FILTER(?match = 1)        
    
}

# Example ?tomato_gene_id = "PGSC0003DMG400027765"
