#+ summary:  List Traitid for given trait_name
#+ tags:
#+  - CandyGene (ListQTL and Genes)

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>

SELECT
   ?qtl
   ?gene
   ?gene_name
WHERE {
   GRAPH <http://europepmc.org/articles> {
      ?qtl a obo:SO_0000771 ;
         so:overlaps ?gene ;
         obo:RO_0003308 ?traitid .
         BIND(uri(concat(obo:, replace(?_traitid, ':', '_'))) AS ?traitid)
   }
   GRAPH <http://solgenomics.net/genome/Solanum_lycopersicum> {
      ?gene rdfs:label ?gene_name ;
         rdf:type obo:SO_0001217.
   }
}
