#+ summary:  List QTLs and associated gene/transcript IDs for the trait days to fruit ripening (SP:0000366).
#+ tags:
#+      - CandyGene (Example 7)
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>

SELECT
   (str(?qtl_id) AS ?qtl_id)
   (str(?sgn_gene_id) AS ?sgn_gene_id)
   (str(?sgn_trans_id) AS ?sgn_trans_id)
   (str(?annot) AS ?annot)
WHERE {
   GRAPH <http://europepmc.org/articles> {
      ?qtl a obo:SO_0000771 ;
         obo:RO_0003308 ?trait ;
         so:overlaps ?gene ;
         dcterms:identifier ?qtl_id .
      FILTER(?trait = obo:SP_0000366)
   }
   GRAPH <http://solgenomics.net/genome/Solanum_lycopersicum> {
      ?gene so:transcribed_to ?transcript ;
         dcterms:identifier ?sgn_gene_id .
      ?transcript rdfs:comment ?annot ;
         dcterms:identifier ?sgn_trans_id
   }
}
LIMIT 5
