PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>

SELECT
   DISTINCT
   str(?gene_id) AS ?gene_id
   str(?ensembl_prot_id) AS ?ensembl_prot_id
   str(?go_term) AS ?term   
FROM NAMED <http://plants.ensembl.org/Solanum_lycopersicum>
FROM NAMED <http://plants.ensembl.org/Solanum_tuberosum>
FROM NAMED <http://www.uniprot.org/proteomes/Solanum_lycopersicum>
FROM NAMED <http://www.uniprot.org/proteomes/Solanum_tuberosum>
FROM NAMED <http://purl.obolibrary.org/obo/go.owl>
   
WHERE {
   GRAPH ?graph_ensembl {
      ?ensembl_prot_id ?rel ?prot.
      ?ensembl_transcript_id so:translates_to ?ensembl_prot_id ;
         so:transcribed_from/dc:identifier ?gene_id .
   }
   FILTER( ?rel IN (<http://rdf.ebi.ac.uk/terms/ensembl/CHECKSUM>, <http://rdf.ebi.ac.uk/terms/ensembl/SEQUENCE_MATCH>) )
   FILTER( ?gene_id IN (%(idList)s) )
   OPTIONAL {
     GRAPH ?graph_uniprot {
        ?prot uniprot:classifiedWith ?go 
     }
     GRAPH ?graph_obo {
        ?go rdfs:label ?go_term  
     }
   }
} 
